"""Roteiros dos episódios — letra e ficha técnica de cada um.

Este é o arquivo criativo do projeto. Tudo o mais (cenas, tempos,
coreografia dos personagens) o `criar_episodio.py` monta a partir daqui,
seguindo a estrutura de episódio da Fase 2.

Regras da letra, da bíblia do canal (Fase 2, seção 5):
  - vocabulário de criança de 1 a 4 anos, palavras concretas
  - refrão repetido no mínimo 4 vezes — repetição é o mecanismo
  - uma ideia por música
  - sem ironia, sem duplo sentido, sem piada pra adulto

A ordem das linhas segue sempre: gancho, refrão, verso 1, verso 2,
refrão final, despedida.
"""

ROTEIROS = [
    {
        "id": "002",
        "pasta": "002-um-dois-coco",
        "titulo": "Um, Dois, Coco",
        "pilar": "dia",
        "ritmo": "samba leve",
        "cenario_a": "coqueiral",
        "cenario_b": "praia",
        "letra": [
            "Quantos cocos tem aqui?",
            "Vamos contar, Maria!",
            "Um, dois, três coquinhos",
            "Quatro, cinco, olha só!",
            "Um, dois, três coquinhos",
            "Vamos contar nós dois!",
            "Um coco na minha mão",
            "Dois coquinhos no chão",
            "Três na cestinha vão",
            "Quatro na barriguinha!",
            "Cinco dedos, olha eu!",
            "Cinco coquinhos são meus",
            "Conta comigo outra vez",
            "Um, dois, três!",
            "Um, dois, três coquinhos",
            "Quatro, cinco, olha só!",
            "Um, dois, três coquinhos",
            "Contamos tudo nós dois!",
            "Tchau, tchau! Até amanhã!",
        ],
    },
    {
        "id": "003",
        "pasta": "003-hora-do-banho",
        "titulo": "Hora do Banho",
        "pilar": "dia",
        "ritmo": "xote",
        "cenario_a": "casa-da-arvore",
        "cenario_b": "praia",
        "letra": [
            "Ó a água quentinha!",
            "Vem tomar banho, Maria",
            "Splash, splash na banheira",
            "Lava, lava a mãozinha",
            "Splash, splash na banheira",
            "Lava toda a criancinha",
            "Lava o pé, lava o pé",
            "Lava a barriga também",
            "Lava a orelha devagar",
            "E o cabelo pra ficar bem",
            "Espuma na cabecinha!",
            "Bolha, bolha, quanta bolha",
            "O patinho vem nadar",
            "E fica aqui comigo",
            "Splash, splash na banheira",
            "Lava, lava a mãozinha",
            "Splash, splash na banheira",
            "Limpa toda a criancinha",
            "Tchau, tchau! Até amanhã!",
        ],
    },
    {
        "id": "004",
        "pasta": "004-que-bicho-e-esse",
        "titulo": "Que Bicho é Esse?",
        "pilar": "dia",
        "ritmo": "frevo",
        "cenario_a": "praia",
        "cenario_b": "coqueiral",
        "letra": [
            "Escuta, escuta o som!",
            "Que bicho será que é?",
            "Que bicho é esse, que bicho é?",
            "Faz assim, faz assim!",
            "Que bicho é esse, que bicho é?",
            "Canta junto aqui comigo!",
            "O passarinho faz piu-piu",
            "O peixinho faz blub-blub",
            "A antinha faz fon-fon",
            "E o caranguejo, tec-tec!",
            "A galinha faz có-có",
            "O sapinho faz cuá-cuá",
            "O grilinho faz cri-cri",
            "E o ventinho faz uuuh",
            "Que bicho é esse, que bicho é?",
            "Faz assim, faz assim!",
            "Que bicho é esse, que bicho é?",
            "Acertamos tudo aqui!",
            "Tchau, tchau! Até amanhã!",
        ],
    },
    {
        "id": "005",
        "pasta": "005-a-fruta-caiu",
        "titulo": "A Fruta Caiu",
        "pilar": "dia",
        "ritmo": "baião",
        "cenario_a": "coqueiral",
        "cenario_b": "praia",
        "letra": [
            "Plim! Caiu uma fruta!",
            "Que fruta será, Nina?",
            "Caiu, caiu a frutinha",
            "Pega do chão, pega já",
            "Caiu, caiu a frutinha",
            "Vamos todos saborear",
            "A banana é compridinha",
            "A laranja é redondinha",
            "O caju é amarelinho",
            "E a manga é bem docinha",
            "Uma fruta pra você",
            "Uma fruta para mim",
            "Uma pro Pipo comer",
            "E uma pro Bolha, enfim!",
            "Caiu, caiu a frutinha",
            "Pega do chão, pega já",
            "Caiu, caiu a frutinha",
            "Comemos tudo por lá",
            "Tchau, tchau! Até amanhã!",
        ],
    },
    {
        "id": "006",
        "pasta": "006-escova-escova",
        "titulo": "Escova, Escova",
        "pilar": "dia",
        "ritmo": "samba leve",
        "cenario_a": "casa-da-arvore",
        "cenario_b": "praia",
        "letra": [
            "Depois de comer, o que faz?",
            "Escova os dentes, Maria!",
            "Escova, escova, escova",
            "Pra cima e pra baixo assim",
            "Escova, escova, escova",
            "Deixa o dente branquinho",
            "Um pouquinho de pastinha",
            "Escova bem devagar",
            "Na frente e atrás também",
            "Agora vem bochechar",
            "Bochecha, bochecha, cospe!",
            "O dentinho tá brilhando",
            "Sorri pra mim, Maria",
            "Que sorriso lindo, olha!",
            "Escova, escova, escova",
            "Pra cima e pra baixo assim",
            "Escova, escova, escova",
            "Ficou tudo limpinho",
            "Tchau, tchau! Até amanhã!",
        ],
    },
    {
        "id": "007",
        "pasta": "007-grande-e-pequeno",
        "titulo": "Grande e Pequeno",
        "pilar": "dia",
        "ritmo": "xote",
        "cenario_a": "coqueiral",
        "cenario_b": "praia",
        "letra": [
            "Olha o coco lá em cima!",
            "É grande ou pequenininho?",
            "Grande, grande, bem grandão",
            "Pequeno, pequenininho",
            "Grande, grande, bem grandão",
            "E pequeno assim, ó!",
            "A Nina é bem grandona",
            "O Pipo é pequenininho",
            "O coqueiro é bem altão",
            "E a formiga, chiquitinha",
            "Abre o braço bem grandão!",
            "Fecha a mão pequenininha",
            "Pula alto, bem grandão!",
            "Agacha pequenininho",
            "Grande, grande, bem grandão",
            "Pequeno, pequenininho",
            "Grande, grande, bem grandão",
            "E pequeno assim, ó!",
            "Tchau, tchau! Até amanhã!",
        ],
    },
    {
        "id": "008",
        "pasta": "008-a-chuva-chegou",
        "titulo": "A Chuva Chegou",
        "pilar": "dia",
        "ritmo": "maracatu suave",
        "cenario_a": "praia",
        "cenario_b": "coqueiral",
        "letra": [
            "Olha a nuvem escurecendo!",
            "Vem chuva na Ilha Pipoca",
            "Chove, chove, chuvinha",
            "Pinga, pinga no chapéu",
            "Chove, chove, chuvinha",
            "Molha tudo, molha o céu",
            "A pinguinha faz plic-plic",
            "A pocinha faz tchibum",
            "O guarda-chuva abre já",
            "E ninguém fica sem um",
            "Parou! Saiu o solzinho",
            "Olha o arco-íris no céu",
            "Vermelho, amarelo, azul",
            "Que bonito, que céu!",
            "Chove, chove, chuvinha",
            "Pinga, pinga no chapéu",
            "Passou, passou a chuvinha",
            "Ficou lindo o nosso céu",
            "Tchau, tchau! Até amanhã!",
        ],
    },
    {
        "id": "009",
        "pasta": "009-como-eu-me-sinto",
        "titulo": "Como Eu Me Sinto",
        "pilar": "dia",
        "ritmo": "xote",
        "cenario_a": "praia",
        "cenario_b": "casa-da-arvore",
        "letra": [
            "Hoje eu tô tão feliz!",
            "E você, como se sente?",
            "Feliz, feliz, bate palma",
            "Triste, triste, faz assim",
            "Feliz, feliz, bate palma",
            "Tá tudo bem por aqui",
            "Quando eu rio, tô feliz",
            "Quando eu choro, tô tristinha",
            "Quando eu pulo, é alegria",
            "E abraço quem tá comigo",
            "Se ficar bravo, respira",
            "Um, dois, três, e passou",
            "Vem cá que eu te abraço",
            "Tá tudo bem, meu amor",
            "Feliz, feliz, bate palma",
            "Triste, triste, faz assim",
            "Feliz, feliz, bate palma",
            "Tá tudo bem por aqui",
            "Tchau, tchau! Até amanhã!",
        ],
    },
    {
        "id": "010",
        "pasta": "010-boa-noite-ilha",
        "titulo": "Boa Noite, Ilha",
        "pilar": "noite",
        "ritmo": "viola",
        "cenario_a": "ceu-noturno",
        "cenario_b": "ceu-noturno",
        "letra": [
            "O sol foi dormir no mar",
            "Chegou a noite na ilha",
            "Boa noite, boa noite",
            "Fecha o olhinho devagar",
            "Boa noite, boa noite",
            "A lua vem te ninar",
            "O passarinho dormiu",
            "O peixinho dormiu",
            "A antinha já ressona",
            "E a ilha adormeceu",
            "A estrela pisca pra você",
            "O vento canta baixinho",
            "A ondinha faz shhh, shhh",
            "Dorme, dorme, meu carinho",
            "Boa noite, boa noite",
            "Fecha o olhinho devagar",
            "Boa noite, boa noite",
            "Até amanhã, meu bem",
        ],
    },
]
